# Generated by Django 4.1 on 2022-08-19 02:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('issue_tracker', '0004_alter_profile_user'),
    ]

    operations = [
        migrations.CreateModel(
            name='Team',
            fields=[
                ('team_id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=1000, unique=True)),
                ('description', models.TextField(default='', max_length=1000)),
                ('created', models.DateField(auto_now_add=True)),
                ('updated', models.DateField(auto_now=True)),
                ('profiles', models.ManyToManyField(to='issue_tracker.profile')),
            ],
        ),
    ]
